# Generated by Django 3.2.3 on 2021-05-23 15:57

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calliope_web', '0002_bss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザー名はすでに使われています。'}, help_text='この項目は必須です。全角文字、半角英数字、@/./+/-/_ でuserから始まる20文字以下の名前にしてください。', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
